import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faHome,
  faUsers,
  faChevronDown,
  faUserPlus,
  faBuilding,
  faTags,
  faChartLine,
  faSignOutAlt,
  faPlusCircle,
  faInbox,
  faPaperPlane,
  faChartBar,
  faTag,
  faPlus,
  faTicket,
  faTachometerAltAverage,
  faMoon,
  faTimes,
  faBellSlash,
  faClock,
  faSpinner,
  faCheckCircle,
  faHourglassHalf,
  faChartPie,
  faCalendarCheck,
  faSearch,
  faChevronLeft,
  faChevronRight,
} from '@fortawesome/free-solid-svg-icons';

import { faBell } from '@fortawesome/free-regular-svg-icons';

const icons = [
  faHome,
  faUsers,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faUserPlus,
  faBuilding,
  faTags,
  faTag,
  faChartLine,
  faSignOutAlt,
  faBell,
  faPlusCircle,
  faInbox,
  faPaperPlane,
  faTicket,
  faChartBar,
  faPlus,
  faTachometerAltAverage,
  faMoon,
  faTimes,
  faBellSlash,
  faClock,
  faSpinner,
  faCheckCircle,
  faHourglassHalf,
  faChartPie,
  faCalendarCheck,
  faSearch,
];

library.add(...icons);
